version: '3.9'
services:
  node:
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "4200:4200"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos

  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos